### ISSUE TITLE
gran permission

### ISSUE THREAD

**Issue by wikett** [sunilbandla/vue-msal-sample#1]
Hi Sunilbandla,

I have a question/problem

I follow your code and everything is fine. I have tested on https://sunilbandla.github.io/vue-msal-sample/ using a corporative account and logs in perfect (mary.thomson@ximbus.onmicrosoft.com), but when I try to log in in my web app(localhost) I get this error:

> You can't access this application 
XimbusTesting needs permission to access resources in your organisation that only an admin can grant. Please ask an admin to grant permission to this app before you can use it. 

Do you know what is the problem? How/Where did you create your App ID to working with microsoft corporative accounts?

(I tested using apps.dev.microsoft.com with "Allow Implicit Flow: True", and I have tried with Azure Active Directory)

I will appreciate it so much.

Thanks in advance.

![grant_permission](https://user-images.githubusercontent.com/3876214/34826248-bdc6f906-f6cd-11e7-9e50-724ab6532646.JPG)

**Comment by sunilbandla** [comment]
I registered my app in apps.dev.microsoft.com. It seems like you are requesting for admin consentable scopes. Try to remove everything in the `delegated permissions` section.

**Comment by wikett** [comment]
Thanks Sunilbandla for your answer.

I think the problem that I have is multi tenant sing in.
