### ISSUE TITLE
UserAgentApplication return null

### ISSUE THREAD

**Issue by jerichosiahaya** [sunilbandla/vue-msal-sample#7]
I tried this sample using my own app registration, I changed the clientId then I can't login at all. The `user` return empty. I think the problem is in my app registration on Azure AD (I don't use AD B2C). Is there anything that I should set on the configuration? This my current configuration on Authentication:

![image](https://user-images.githubusercontent.com/47173293/156359426-2ad73159-9bd9-48ec-b896-51111a23b7fe.png)

**Comment by sunilbandla** [comment]
Hi Jericho,

I'm not sure what's wrong in the config here. Could you please post on
Stackoverflow too?

Thanks.

**Comment by jerichosiahaya** [comment]
Okay, it's totally my bad. I changed the code into this:
```
this.applicationConfig = {
      clientID: 'XXXXXXXXXXXX',
      tenantID: 'XXXXXXXXXXX',
      graphScopes: ['user.read']
    };
    this.app = new Msal.UserAgentApplication(
      this.applicationConfig.clientID,
      this.applicationConfig.authority,
    );
```
